apiVersion: batch/v1
kind: Job
metadata:
  name: influx-metrics-deployer
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: influx-scripts     # must match the ConfigMap we created above!
            items:
              - key: run_Influx.sh
                path: /scripts/run_Influx.sh
      containers:
        - name: runner
          image: alpine:3.18
          command: ["/bin/sh", "-c"]
          args: ["/scripts/run_Influx.sh"]
          volumeMounts:
            - name: script-volume
              mountPath: /scripts  # where the file will be placed in the container
