## cert-manager HelmChart configuration
## https://github.com/cert-manager/cert-manager

# Enable deployment of cert-manager CRDs
# (Note: For v1.14+, CRDs are installed separately or use helm values below)

installCRDs: false

extraArgs:
  - --enable-cni
  - --leader-elect

replicas: 2

service:
  type: ClusterIP

dnsChallenge:
  provider: route53

rbac:
  create: true

serviceMonitor:
  enabled: false

podDnsPolicy: "ClusterFirst"
podDnsConfig:
  nameservers:
    - "192.168.30.121"
