apiVersion: v1
kind: Secret
metadata:
  name: flux-gitops
  namespace: flux-system
type: Opaque
stringData:
  username: "YOUR_GITHUB_USERNAME"
  password: "YOUR_GITHUB_TOKEN_OR_PAT"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-repository
  namespace: flux-system
spec:
  type: github
  interval: 1m
  url: https://github.com/ChadEngel/ce-ai-home-lab
  ref:
    branch: main
  secretRef:
    name: gitops-auth
