apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infisical-ssl-certs
  namespace: ai
spec:
  secretName: infisical-ssl-certs
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "secrets.caehomelab.com"
  dnsNames:
    - secrets.caehomelab.com

