apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - serviceaccount.yaml
  - rbac.yaml
  - storageclass.yaml
  - deployment.yaml

# Common labels applied to namespaced resources (SA, Deployment).
labels:
  - includeSelectors: true
    pairs:
      app: nfs-subdir-external-provisioner